<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
global $wpdb;
$patients = $this->get_active_patients( 500 );
$edit_id  = isset( $_GET['family_member_id'] ) ? absint( $_GET['family_member_id'] ) : 0;
$member   = $edit_id ? CAS_Patient::get_family_member( $edit_id ) : null;
$table    = CAS_DB::table( 'family_members' );
$pt       = CAS_DB::table( 'patients' );
$members  = $wpdb->get_results( "SELECT f.*, p.full_name AS primary_name, p.mobile AS primary_mobile FROM {$table} f LEFT JOIN {$pt} p ON p.id = f.primary_id ORDER BY f.is_active DESC, f.created_at DESC LIMIT 200" );
$relations = CAS_Patient::relation_options();
$blood_groups = CAS_Patient::blood_group_options();
$age = $member ? CAS_Patient::calculate_age( $member->date_of_birth ) : '';
?>
<div class="wrap cas-admin-wrap">
	<h1><?php echo esc_html__( 'Family Members', 'cas' ); ?></h1>
	<div class="cas-two-column">
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cas-card cas-form cas-labelled-form">
			<h2><?php echo $member ? esc_html__( 'Edit Family Member', 'cas' ) : esc_html__( 'Add Family Member', 'cas' ); ?></h2>
			<input type="hidden" name="action" value="cas_save_family_member"><input type="hidden" name="family_member_id" value="<?php echo esc_attr( $edit_id ); ?>"><?php wp_nonce_field( 'cas_save_family_member' ); ?>
			<p><label for="cas-family-primary"><strong><?php echo esc_html__( 'Primary Patient', 'cas' ); ?></strong></label><select id="cas-family-primary" name="primary_id" class="widefat" required><option value=""><?php echo esc_html__( 'Select primary patient', 'cas' ); ?></option><?php foreach ( $patients as $patient ) : ?><option value="<?php echo esc_attr( $patient->id ); ?>" <?php selected( $member ? $member->primary_id : 0, $patient->id ); ?>><?php echo esc_html( $patient->full_name . ' — ' . $patient->mobile ); ?></option><?php endforeach; ?></select></p>
			<div class="cas-form-grid">
				<p><label for="cas-family-name"><strong><?php echo esc_html__( 'Family Member Full Name', 'cas' ); ?></strong></label><input type="text" id="cas-family-name" name="full_name" class="widefat" required value="<?php echo esc_attr( $member ? $member->full_name : '' ); ?>"></p>
				<p><label for="cas-family-relation"><strong><?php echo esc_html__( 'Relation', 'cas' ); ?></strong></label><select id="cas-family-relation" name="relation" class="widefat" required><option value=""><?php echo esc_html__( 'Select relation', 'cas' ); ?></option><?php foreach ( $relations as $relation ) : ?><option value="<?php echo esc_attr( $relation ); ?>" <?php selected( $member ? $member->relation : '', $relation ); ?>><?php echo esc_html( $relation ); ?></option><?php endforeach; ?></select></p>
				<p><label for="cas-family-age"><strong><?php echo esc_html__( 'Age', 'cas' ); ?></strong></label><input type="number" min="0" max="125" id="cas-family-age" name="age" class="widefat" value="<?php echo esc_attr( $age ); ?>"></p>
				<p><label><strong><?php echo esc_html__( 'DOB Calculated', 'cas' ); ?></strong></label><input type="text" class="widefat" readonly value="<?php echo esc_attr( $member ? $member->date_of_birth : '' ); ?>"></p>
				<p><label for="cas-family-gender"><strong><?php echo esc_html__( 'Gender', 'cas' ); ?></strong></label><select id="cas-family-gender" name="gender" class="widefat"><option value=""><?php echo esc_html__( 'Select gender', 'cas' ); ?></option><option value="male" <?php selected( $member ? $member->gender : '', 'male' ); ?>><?php echo esc_html__( 'Male', 'cas' ); ?></option><option value="female" <?php selected( $member ? $member->gender : '', 'female' ); ?>><?php echo esc_html__( 'Female', 'cas' ); ?></option><option value="other" <?php selected( $member ? $member->gender : '', 'other' ); ?>><?php echo esc_html__( 'Other', 'cas' ); ?></option></select></p>
				<p><label for="cas-family-blood"><strong><?php echo esc_html__( 'Blood Group', 'cas' ); ?></strong></label><select id="cas-family-blood" name="blood_group" class="widefat"><option value=""><?php echo esc_html__( 'Select', 'cas' ); ?></option><?php foreach ( $blood_groups as $bg ) : ?><option value="<?php echo esc_attr( $bg ); ?>" <?php selected( $member ? $member->blood_group : '', $bg ); ?>><?php echo esc_html( $bg ); ?></option><?php endforeach; ?></select></p>
			</div>
			<p><label for="cas-family-notes"><strong><?php echo esc_html__( 'Notes', 'cas' ); ?></strong></label><textarea id="cas-family-notes" name="notes" class="widefat" rows="3"><?php echo esc_textarea( $member ? $member->notes : '' ); ?></textarea></p>
			<p><label for="cas-family-active"><input type="checkbox" id="cas-family-active" name="is_active" value="1" <?php checked( $member ? $member->is_active : 1, 1 ); ?>> <?php echo esc_html__( 'Family member is active', 'cas' ); ?></label></p>
			<?php submit_button( $member ? __( 'Update Family Member', 'cas' ) : __( 'Add Family Member', 'cas' ) ); ?><?php if ( $member ) : ?><a class="button" href="<?php echo esc_url( admin_url( 'admin.php?page=cas-family-members' ) ); ?>"><?php echo esc_html__( 'Cancel Edit', 'cas' ); ?></a><?php endif; ?>
		</form>
		<div class="cas-card"><h2><?php echo esc_html__( 'Family Member List', 'cas' ); ?></h2><table class="widefat striped"><thead><tr><th><?php echo esc_html__( 'Family Member', 'cas' ); ?></th><th><?php echo esc_html__( 'Primary Patient', 'cas' ); ?></th><th><?php echo esc_html__( 'Relation', 'cas' ); ?></th><th><?php echo esc_html__( 'Age', 'cas' ); ?></th><th><?php echo esc_html__( 'Active', 'cas' ); ?></th><th><?php echo esc_html__( 'Actions', 'cas' ); ?></th></tr></thead><tbody><?php if ( empty( $members ) ) : ?><tr><td colspan="6"><?php echo esc_html__( 'No family members found.', 'cas' ); ?></td></tr><?php else : ?><?php foreach ( $members as $row ) : ?><tr><td><?php echo esc_html( $row->full_name ); ?></td><td><?php echo esc_html( $row->primary_name . ( $row->primary_mobile ? ' — ' . $row->primary_mobile : '' ) ); ?></td><td><?php echo esc_html( $row->relation ); ?></td><td><?php echo esc_html( CAS_Patient::calculate_age( $row->date_of_birth ) ); ?></td><td><?php echo $row->is_active ? esc_html__( 'Yes', 'cas' ) : esc_html__( 'No', 'cas' ); ?></td><td><a href="<?php echo esc_url( admin_url( 'admin.php?page=cas-family-members&family_member_id=' . absint( $row->id ) ) ); ?>"><?php echo esc_html__( 'Edit', 'cas' ); ?></a><?php if ( $row->is_active ) : ?> | <a href="<?php echo esc_url( wp_nonce_url( add_query_arg( array( 'action' => 'cas_deactivate_family_member', 'family_member_id' => absint( $row->id ) ), admin_url( 'admin-post.php' ) ), 'cas_deactivate_family_member_' . absint( $row->id ) ) ); ?>"><?php echo esc_html__( 'Deactivate', 'cas' ); ?></a><?php endif; ?> | <a class="cas-danger-link" href="<?php echo esc_url( wp_nonce_url( add_query_arg( array( 'action' => 'cas_delete_family_member', 'family_member_id' => absint( $row->id ) ), admin_url( 'admin-post.php' ) ), 'cas_delete_family_member_' . absint( $row->id ) ) ); ?>" onclick="return confirm('<?php echo esc_js( __( 'Delete this family member permanently?', 'cas' ) ); ?>')"><?php echo esc_html__( 'Delete', 'cas' ); ?></a></td></tr><?php endforeach; ?><?php endif; ?></tbody></table></div>
	</div>
</div>
