<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$search  = isset( $_GET['s'] ) ? sanitize_text_field( wp_unslash( $_GET['s'] ) ) : '';
$edit_id = isset( $_GET['patient_id'] ) ? absint( $_GET['patient_id'] ) : 0;
$patient = $edit_id ? CAS_Patient::get_by_id( $edit_id ) : null;
$patients = CAS_Patient::search( array( 'search' => $search, 'limit' => 200 ) );
$blood_groups = CAS_Patient::blood_group_options();
$age = $patient ? CAS_Patient::calculate_age( $patient->date_of_birth ) : '';
?>
<div class="wrap cas-admin-wrap">
	<h1><?php echo esc_html__( 'Patients', 'cas' ); ?></h1>
	<p class="description"><?php echo esc_html__( 'Create and manage chamber patient profiles. Age is entered by user/admin; DOB Calculated is stored for future age calculation.', 'cas' ); ?></p>
	<form method="get" class="cas-filter-bar"><input type="hidden" name="page" value="cas-patients"><label for="cas-patient-search" class="cas-inline-label"><?php echo esc_html__( 'Search patients', 'cas' ); ?></label><input id="cas-patient-search" type="search" name="s" value="<?php echo esc_attr( $search ); ?>" placeholder="<?php echo esc_attr__( 'Name, mobile, or email', 'cas' ); ?>"><button class="button button-primary"><?php echo esc_html__( 'Search', 'cas' ); ?></button><a class="button" href="<?php echo esc_url( admin_url( 'admin.php?page=cas-patients' ) ); ?>"><?php echo esc_html__( 'Reset', 'cas' ); ?></a></form>
	<div class="cas-two-column">
		<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="cas-card cas-form cas-labelled-form">
			<h2><?php echo $patient ? esc_html__( 'Edit Patient', 'cas' ) : esc_html__( 'Create New Patient', 'cas' ); ?></h2>
			<input type="hidden" name="action" value="cas_save_patient"><input type="hidden" name="patient_id" value="<?php echo esc_attr( $edit_id ); ?>"><?php wp_nonce_field( 'cas_save_patient' ); ?>
			<div class="cas-form-grid">
				<p><label for="cas-full-name"><?php echo esc_html__( 'New Patient Name / Full Name', 'cas' ); ?> *</label><input id="cas-full-name" name="full_name" class="widefat" required value="<?php echo esc_attr( $patient ? $patient->full_name : '' ); ?>"></p>
				<p><label for="cas-mobile"><?php echo esc_html__( 'Mobile Number', 'cas' ); ?> *</label><input id="cas-mobile" name="mobile" class="widefat" required placeholder="01XXXXXXXXX" value="<?php echo esc_attr( $patient ? $patient->mobile : '' ); ?>"><span class="description"><?php echo esc_html__( 'Accepted: 01XXXXXXXXX or 8801XXXXXXXXX.', 'cas' ); ?></span></p>
				<p><label for="cas-age"><?php echo esc_html__( 'Age', 'cas' ); ?> *</label><input id="cas-age" type="number" min="0" max="125" name="age" class="widefat" value="<?php echo esc_attr( $age ); ?>" required></p>
				<p><label><?php echo esc_html__( 'DOB Calculated', 'cas' ); ?></label><input type="text" class="widefat" value="<?php echo esc_attr( $patient ? $patient->date_of_birth : '' ); ?>" readonly><span class="description"><?php echo esc_html__( 'Automatically calculated from age and stored internally.', 'cas' ); ?></span></p>
				<p><label for="cas-gender"><?php echo esc_html__( 'Gender', 'cas' ); ?> *</label><select id="cas-gender" name="gender" class="widefat" required><option value=""><?php echo esc_html__( 'Select', 'cas' ); ?></option><option value="male" <?php selected( $patient ? $patient->gender : '', 'male' ); ?>><?php echo esc_html__( 'Male', 'cas' ); ?></option><option value="female" <?php selected( $patient ? $patient->gender : '', 'female' ); ?>><?php echo esc_html__( 'Female', 'cas' ); ?></option><option value="other" <?php selected( $patient ? $patient->gender : '', 'other' ); ?>><?php echo esc_html__( 'Other', 'cas' ); ?></option></select></p>
				<p><label for="cas-blood"><?php echo esc_html__( 'Blood Group', 'cas' ); ?></label><select id="cas-blood" name="blood_group" class="widefat"><option value=""><?php echo esc_html__( 'Select', 'cas' ); ?></option><?php foreach ( $blood_groups as $bg ) : ?><option value="<?php echo esc_attr( $bg ); ?>" <?php selected( $patient ? $patient->blood_group : '', $bg ); ?>><?php echo esc_html( $bg ); ?></option><?php endforeach; ?></select></p>
				<p><label for="cas-city"><?php echo esc_html__( 'City', 'cas' ); ?></label><input id="cas-city" name="city" class="widefat" value="<?php echo esc_attr( $patient ? $patient->city : '' ); ?>"></p>
				<p><label for="cas-email"><?php echo esc_html__( 'Email', 'cas' ); ?></label><input id="cas-email" type="email" name="email" class="widefat" value="<?php echo esc_attr( $patient ? $patient->email : '' ); ?>"></p>
				<p class="cas-form-wide"><label for="cas-address"><?php echo esc_html__( 'Address', 'cas' ); ?> *</label><textarea id="cas-address" name="address" class="widefat" rows="2" required><?php echo esc_textarea( $patient ? $patient->address : '' ); ?></textarea></p>
				<p class="cas-form-wide"><label for="cas-notes"><?php echo esc_html__( 'Notes', 'cas' ); ?></label><textarea id="cas-notes" name="notes" class="widefat" rows="2"><?php echo esc_textarea( $patient ? $patient->notes : '' ); ?></textarea></p>
			</div>
			<p><label><input type="checkbox" name="is_active" value="1" <?php checked( $patient ? $patient->is_active : 1, 1 ); ?>> <?php echo esc_html__( 'Active patient', 'cas' ); ?></label></p>
			<?php submit_button( $patient ? __( 'Update Patient', 'cas' ) : __( 'Create Patient', 'cas' ) ); ?><?php if ( $patient ) : ?><a class="button" href="<?php echo esc_url( admin_url( 'admin.php?page=cas-patients' ) ); ?>"><?php echo esc_html__( 'Cancel Edit', 'cas' ); ?></a><?php endif; ?>
		</form>
		<div class="cas-card"><h2><?php echo esc_html__( 'Patient List', 'cas' ); ?></h2><table class="widefat striped"><thead><tr><th><?php echo esc_html__( 'Name', 'cas' ); ?></th><th><?php echo esc_html__( 'Mobile', 'cas' ); ?></th><th><?php echo esc_html__( 'Age', 'cas' ); ?></th><th><?php echo esc_html__( 'Gender', 'cas' ); ?></th><th><?php echo esc_html__( 'Status', 'cas' ); ?></th><th><?php echo esc_html__( 'Actions', 'cas' ); ?></th></tr></thead><tbody>
		<?php foreach ( $patients as $row ) : ?><tr class="<?php echo $row->is_active ? '' : 'cas-inactive-record'; ?>"><td><strong><?php echo esc_html( $row->full_name ); ?></strong></td><td><?php echo esc_html( $row->mobile ); ?></td><td><?php echo esc_html( CAS_Patient::calculate_age( $row->date_of_birth ) ); ?></td><td><?php echo esc_html( ucfirst( (string) $row->gender ) ); ?></td><td><span class="<?php echo $row->is_active ? 'cas-status-active' : 'cas-status-inactive'; ?>"><?php echo $row->is_active ? esc_html__( 'Active', 'cas' ) : esc_html__( 'Inactive', 'cas' ); ?></span></td><td><a href="<?php echo esc_url( admin_url( 'admin.php?page=cas-patients&patient_id=' . absint( $row->id ) ) ); ?>"><?php echo esc_html__( 'Edit', 'cas' ); ?></a> | <a href="<?php echo esc_url( wp_nonce_url( add_query_arg( array( 'action' => 'cas_deactivate_patient', 'patient_id' => absint( $row->id ) ), admin_url( 'admin-post.php' ) ), 'cas_deactivate_patient_' . absint( $row->id ) ) ); ?>"><?php echo esc_html__( 'Deactivate', 'cas' ); ?></a> | <a class="cas-danger-link" href="<?php echo esc_url( wp_nonce_url( add_query_arg( array( 'action' => 'cas_delete_patient', 'patient_id' => absint( $row->id ) ), admin_url( 'admin-post.php' ) ), 'cas_delete_patient_' . absint( $row->id ) ) ); ?>" onclick="return confirm('<?php echo esc_js( __( 'Delete this patient permanently?', 'cas' ) ); ?>')"><?php echo esc_html__( 'Delete', 'cas' ); ?></a></td></tr><?php endforeach; ?>
		<?php if ( empty( $patients ) ) : ?><tr><td colspan="6"><?php echo esc_html__( 'No patients found.', 'cas' ); ?></td></tr><?php endif; ?></tbody></table></div>
	</div>
</div>
