<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
class CAS_Waiting_List {
	private static function date($d){$d=sanitize_text_field((string)$d);return preg_match('/^\d{4}-\d{2}-\d{2}$/',$d)?$d:'';}
	public static function get_queue_number($doctor_id,$date){ global $wpdb; $date=self::date($date); $t=CAS_DB::table('waiting_list'); return absint($wpdb->get_var($wpdb->prepare("SELECT MAX(queue_number) FROM {$t} WHERE doctor_id=%d AND appointment_date=%s",absint($doctor_id),$date)))+1; }
	public static function add_to_list($data){ global $wpdb; $doctor=absint($data['doctor_id']??0); $patient=absint($data['patient_id']??0); $date=self::date($data['appointment_date']??''); if(!$doctor||!$patient||!$date){return new WP_Error('cas_waiting_required',__('Doctor, patient, and date are required.','cas'));} $t=CAS_DB::table('waiting_list'); $duplicate=$wpdb->get_var($wpdb->prepare("SELECT id FROM {$t} WHERE doctor_id=%d AND patient_id=%d AND appointment_date=%s AND status='waiting' LIMIT 1",$doctor,$patient,$date)); if($duplicate){return new WP_Error('cas_waiting_duplicate',__('This patient is already waiting for the selected doctor and date.','cas'));} $q=self::get_queue_number($doctor,$date); $ok=$wpdb->insert(CAS_DB::table('waiting_list'),array('doctor_id'=>$doctor,'patient_id'=>$patient,'appointment_date'=>$date,'queue_number'=>$q,'status'=>'waiting','created_at'=>CAS_DB::now(),'updated_at'=>CAS_DB::now()),array('%d','%d','%s','%d','%s','%s','%s')); $id = $ok ? absint( $wpdb->insert_id ) : 0; if ( $id && empty( $data['suppress_notification'] ) ) { $w = self::get_by_id( $id ); if ( $w && ! empty( $w->patient_mobile ) ) { CAS_SMS::send_template( 'waiting_list_joined', $w->patient_mobile, array( 'patient_name' => $w->patient_name, 'doctor_name' => $w->doctor_name, 'date' => $w->appointment_date, 'queue_number' => $w->queue_number ), null, 'waiting_list' ); } } return $id ? $id : new WP_Error('cas_waiting_failed',__('Could not join waiting list.','cas')); }
	public static function promote_to_appointment($waiting_id,$serial_number=0,$booked_by=0,$override_date=''){ global $wpdb; $w=self::get_by_id($waiting_id); if(!$w||'waiting'!==$w->status){return new WP_Error('cas_waiting_invalid',__('Waiting entry cannot be promoted.','cas'));} $id=CAS_Appointment::create(array('doctor_id'=>$w->doctor_id,'patient_id'=>$w->patient_id,'appointment_date'=>( self::date($override_date) ? self::date($override_date) : $w->appointment_date ),'serial_number'=>absint($serial_number),'booked_by'=>absint($booked_by),'source'=>'waiting_list','status'=>'moved_from_waiting')); if(is_wp_error($id)){return $id;} $wpdb->update(CAS_DB::table('waiting_list'),array('status'=>'promoted','promoted_appointment_id'=>absint($id),'updated_at'=>CAS_DB::now()),array('id'=>absint($waiting_id)),array('%s','%d','%s'),array('%d')); $a = CAS_Appointment::get_by_id( absint( $id ) ); if ( $a && ! empty( $a->patient_mobile ) ) { $ph = CAS_Appointment::get_sms_placeholders( $a ); $ph['queue_number'] = $w->queue_number; CAS_SMS::send_template( 'waiting_list_promoted', $a->patient_mobile, $ph, absint( $id ), 'waiting_list' ); } return absint($id); }
	public static function get_by_id($id){ global $wpdb; $w=CAS_DB::table('waiting_list'); $p=CAS_DB::table('patients'); $d=CAS_DB::table('doctors'); return $wpdb->get_row($wpdb->prepare("SELECT w.*,p.full_name patient_name,p.mobile patient_mobile,d.name doctor_name FROM {$w} w LEFT JOIN {$p} p ON p.id=w.patient_id LEFT JOIN {$d} d ON d.id=w.doctor_id WHERE w.id=%d",absint($id))); }
	public static function get_by_date_doctor($date,$doctor_id,$status=''){ global $wpdb; $date=self::date($date); $w=CAS_DB::table('waiting_list'); $p=CAS_DB::table('patients'); $d=CAS_DB::table('doctors'); $where='w.doctor_id=%d AND w.appointment_date=%s'; $v=array(absint($doctor_id),$date); if($status){$where.=' AND w.status=%s';$v[]=sanitize_key($status);} return $wpdb->get_results($wpdb->prepare("SELECT w.*,p.full_name patient_name,p.mobile patient_mobile,d.name doctor_name FROM {$w} w LEFT JOIN {$p} p ON p.id=w.patient_id LEFT JOIN {$d} d ON d.id=w.doctor_id WHERE {$where} ORDER BY w.queue_number ASC",$v)); }
	public static function cancel_waiting($id){ global $wpdb; return false!==$wpdb->update(CAS_DB::table('waiting_list'),array('status'=>'cancelled','updated_at'=>CAS_DB::now()),array('id'=>absint($id)),array('%s','%s'),array('%d')); }
}
