<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$patient = $this->get_current_patient();
$appointments = $patient ? $this->get_patient_appointments( $patient->id ) : array();
$waiting_rows = $this->get_waiting_list_rows();
$settings = CAS_DB::get_settings();
$booking_url = $this->page_url( absint( $settings['portal_booking_page_id'] ?? 0 ) );
?>
<div class="cas-public-wrap cas-appointments-wrap" data-cas-component="my-appointments">
	<header class="cas-page-heading"><span class="cas-page-icon" aria-hidden="true">🗓</span><div><h2><?php echo esc_html__( 'My Appointments', 'cas' ); ?></h2><p><?php echo esc_html__( 'One active appointment is allowed for each patient profile. After chamber reconfirmation, please call the chamber manager for any change or cancellation.', 'cas' ); ?></p></div></header>
	<div class="cas-alert" data-cas-alert hidden></div>
	<section class="cas-card"><div class="cas-list-heading"><h3><?php echo esc_html__( 'Appointments', 'cas' ); ?></h3></div>
		<?php if ( empty( $appointments ) ) : ?><div class="cas-empty-state"><span aria-hidden="true">📅</span><p><?php echo esc_html__( 'No appointments found yet.', 'cas' ); ?></p><a class="cas-button cas-button-primary" href="<?php echo esc_url( $booking_url ); ?>"><?php echo esc_html__( 'Book an Appointment', 'cas' ); ?></a></div><?php else : ?><div class="cas-appointment-list"><?php foreach ( $appointments as $appointment ) : $manageable = CAS_Appointment::is_patient_manageable( $appointment ); ?><article class="cas-appointment-list-card"><div class="cas-appointment-list-top"><div class="cas-appointment-people"><div class="cas-appointment-person cas-appointment-doctor"><span class="cas-person-label"><span aria-hidden="true">👨‍⚕️</span><?php echo esc_html__( 'Doctor', 'cas' ); ?></span><span class="cas-person-name"><?php echo esc_html( $appointment->doctor_name ); ?></span></div><div class="cas-appointment-person cas-appointment-patient"><span class="cas-person-label"><span aria-hidden="true">👤</span><?php echo esc_html__( 'Patient', 'cas' ); ?></span><strong class="cas-person-name"><?php echo esc_html( $appointment->patient_name ); ?></strong></div></div><span class="cas-status-badge cas-status-<?php echo esc_attr( $appointment->status ); ?>"><?php echo esc_html( ucwords( str_replace( '_', ' ', $appointment->status ) ) ); ?></span></div><div class="cas-appointment-list-meta"><span><b aria-hidden="true">▣</b><?php echo esc_html( $this->format_date( $appointment->appointment_date ) ); ?></span><span><b aria-hidden="true">◷</b><?php echo esc_html( $this->format_time( $appointment->reporting_time ) ); ?></span><span><b aria-hidden="true">#</b><?php echo ! empty( $appointment->is_vip ) ? esc_html__( 'VIP appointment', 'cas' ) : esc_html( sprintf( __( 'Serial %d', 'cas' ), absint( $appointment->serial_number ) ) ); ?></span></div><?php if ( $manageable ) : ?><div class="cas-appointment-actions"><a class="cas-button cas-button-secondary" href="<?php echo esc_url( add_query_arg( 'cas_edit_appointment', absint( $appointment->id ), $booking_url ) ); ?>"><?php echo esc_html__( 'Modify', 'cas' ); ?></a><button type="button" class="cas-button cas-button-danger" data-cas-cancel-appointment="<?php echo esc_attr( $appointment->id ); ?>"><?php echo esc_html__( 'Cancel Appointment', 'cas' ); ?></button></div><?php elseif ( CAS_Appointment::is_active_for_patient( $appointment ) ) : ?><p class="cas-appointment-help"><?php echo esc_html( CAS_Appointment::patient_management_lock_message( $appointment ) ); ?></p><?php endif; ?></article><?php endforeach; ?></div><?php endif; ?>
	</section>
	<section class="cas-card"><div class="cas-list-heading"><h3><?php echo esc_html__( 'Waiting List Status', 'cas' ); ?></h3></div><?php if ( empty( $waiting_rows ) ) : ?><div class="cas-empty-state cas-empty-small"><p><?php echo esc_html__( 'No waiting-list requests found.', 'cas' ); ?></p></div><?php else : ?><div class="cas-appointment-list"><?php foreach ( $waiting_rows as $row ) : ?><article class="cas-appointment-list-card cas-waiting-list-card"><div class="cas-appointment-list-top"><div class="cas-appointment-people"><div class="cas-appointment-person cas-appointment-doctor"><span class="cas-person-label"><span aria-hidden="true">👨‍⚕️</span><?php echo esc_html__( 'Doctor', 'cas' ); ?></span><span class="cas-person-name"><?php echo esc_html( $row->doctor_name ); ?></span></div><div class="cas-appointment-person cas-appointment-patient"><span class="cas-person-label"><span aria-hidden="true">👤</span><?php echo esc_html__( 'Patient', 'cas' ); ?></span><strong class="cas-person-name"><?php echo esc_html( $row->patient_name ); ?></strong></div></div><span class="cas-status-badge cas-status-waiting_list"><?php echo esc_html( ucwords( str_replace( '_', ' ', $row->status ) ) ); ?></span></div><div class="cas-appointment-list-meta"><span><b aria-hidden="true">▣</b><?php echo esc_html( $this->format_date( $row->appointment_date ) ); ?></span><span><b aria-hidden="true">#</b><?php echo esc_html( sprintf( __( 'Queue %d', 'cas' ), absint( $row->queue_number ) ) ); ?></span></div></article><?php endforeach; ?></div><?php endif; ?></section>
</div>
